[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
kzyno = "Har3kPZU49yuvD7etW76fMcj3AW83Q1TbRkz1Y9RjCdv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "../../wallets/kzy2HnRf46r9zNvAuxhwoJcZrYVTQtTToZ7RNsHwsA4.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/kzyno.ts"
init = "yarn run ts-node scripts/init.ts"
